module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // FilterNest Customer Color Scheme (Original PureFlow)
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#321200",
        "on-tertiary-fixed-variant": "#474836",
        "on-surface": "#1a1c1a",
        "surface-variant": "#e3e2e0",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1a",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f2f1ee",
        "primary-fixed-dim": "#ffb68c",
        "surface-container": "#efeeeb",
        "surface-dim": "#dbdad7",
        "inverse-surface": "#2f312f",
        "on-primary-container": "#ffc29f",
        "on-tertiary-container": "#d1d1b9",
        "tertiary-container": "#585a47",
        "on-secondary-container": "#706439",
        "surface-bright": "#faf9f6",
        "tertiary": "#414231",
        "outline": "#877369",
        "primary": "#6c2f00",
        "secondary-container": "#f3e2ac",
        "on-tertiary-fixed": "#1b1d0e",
        "surface": "#faf9f6",
        "outline-variant": "#dac2b6",
        "surface-tint": "#934b19",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb68c",
        "secondary-fixed": "#f3e2ac",
        "surface-container-low": "#f4f3f1",
        "secondary": "#6a5e33",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c8b0",
        "primary-fixed": "#ffdbc9",
        "on-primary-fixed-variant": "#753401",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#d6c692",
        "tertiary-fixed": "#e4e4cc",
        "primary-container": "#8b4513",
        "on-secondary-fixed": "#231b00",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e3e2e0",
        "on-secondary-fixed-variant": "#51461e",
        "surface-container-high": "#e9e8e5",
        "on-surface-variant": "#54433a",
        "background": "#faf9f6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "8px",
      },
      maxWidth: {
        "max-width": "1440px",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #6c2f00 0%, #8b4513 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
