module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // FilterNest Agent Color Scheme (Teal/Blue Field Workforce)
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002020",
        "on-tertiary-fixed-variant": "#474836",
        "on-surface": "#1a1c1a",
        "surface-variant": "#e0e3e1",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1a",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eff1ee",
        "primary-fixed-dim": "#6dd9d5",
        "surface-container": "#ecefec",
        "surface-dim": "#d9dcd9",
        "inverse-surface": "#2e3130",
        "on-primary-container": "#a0f0ec",
        "on-tertiary-container": "#d1d1b9",
        "tertiary-container": "#585a47",
        "on-secondary-container": "#4a6361",
        "surface-bright": "#f7faf7",
        "tertiary": "#414231",
        "outline": "#6f7978",
        "primary": "#006a68",
        "secondary-container": "#cce8e6",
        "on-tertiary-fixed": "#1b1d0e",
        "surface": "#f7faf7",
        "outline-variant": "#bec9c7",
        "surface-tint": "#008583",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#6dd9d5",
        "secondary-fixed": "#cce8e6",
        "surface-container-low": "#f1f4f1",
        "secondary": "#4a6361",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c8b0",
        "primary-fixed": "#a0f0ec",
        "on-primary-fixed-variant": "#00504e",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b0ccca",
        "tertiary-fixed": "#e4e4cc",
        "primary-container": "#005352",
        "on-secondary-fixed": "#051f1e",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e1",
        "on-secondary-fixed-variant": "#324b49",
        "surface-container-high": "#e6e9e6",
        "on-surface-variant": "#3f4947",
        "background": "#f7faf7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "gutter": "20px",
        "unit": "8px",
      },
      maxWidth: {
        "max-width": "1440px",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #006a68 0%, #008583 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
