module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // FilterNest Admin Color Scheme (Dark Enterprise Control)
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0d1b3a",
        "on-tertiary-fixed-variant": "#474836",
        "on-surface": "#1a1c1e",
        "surface-variant": "#e0e2e8",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1c1e",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f0f0f5",
        "primary-fixed-dim": "#b0c6ff",
        "surface-container": "#edeef3",
        "surface-dim": "#d9dade",
        "inverse-surface": "#2e3036",
        "on-primary-container": "#c4d6ff",
        "on-tertiary-container": "#d1d1b9",
        "tertiary-container": "#585a47",
        "on-secondary-container": "#5a5d6e",
        "surface-bright": "#f8f9fe",
        "tertiary": "#414231",
        "outline": "#74777f",
        "primary": "#1b3a6b",
        "secondary-container": "#dee1f2",
        "on-tertiary-fixed": "#1b1d0e",
        "surface": "#f8f9fe",
        "outline-variant": "#c3c6cf",
        "surface-tint": "#3b5ba9",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b0c6ff",
        "secondary-fixed": "#dee1f2",
        "surface-container-low": "#f2f3f8",
        "secondary": "#5a5d6e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c8b0",
        "primary-fixed": "#d9e2ff",
        "on-primary-fixed-variant": "#274390",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c2c5d6",
        "tertiary-fixed": "#e4e4cc",
        "primary-container": "#274390",
        "on-secondary-fixed": "#171a2c",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e2e8",
        "on-secondary-fixed-variant": "#424556",
        "surface-container-high": "#e7e8ed",
        "on-surface-variant": "#43474e",
        "background": "#f8f9fe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "8px",
      },
      maxWidth: {
        "max-width": "1440px",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #1b3a6b 0%, #274390 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'bounce-slow': 'bounce 2s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
